{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y python sudo bash ca-certificates && apt-get clean; \
    elif [ $(command -v dnf) ] && [ $(cat /etc/os-release | grep VERSION_ID | sed -e 's|[A-Z_=]||g') -ge 23 ]; then dnf makecache && dnf --assumeyes install python3-devel python3-dnf sudo bash which && dnf clean all; \
    elif [ $(command -v dnf) ] && [ $(cat /etc/os-release | grep VERSION_ID | sed -e 's|[A-Z_=]||g') -le 22 ]; then dnf makecache && dnf --assumeyes install python-devel python-dnf sudo bash which && dnf clean all; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum install -y libselinux-python python sudo yum-plugin-ovl bash && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    elif [ $(command -v zypper) ]; then zypper refresh && zypper install -y python sudo bash python-xml && zypper clean -a; \
    elif [ $(command -v apk) ]; then apk update && apk add --no-cache python sudo bash ca-certificates; \
    elif [ $(command -v xbps-install) ]; then xbps-install -Syu && xbps-install -y python sudo bash ca-certificates && xbps-remove -O; fi
